GET http://localhost:8090/weather/03132010

###
GET http://localhost:8090/weather/20010010

###

GET http://api.weatherapi.com/v1/current.json?q=Rio de Janeiro

Key: b0521787020347eca0b22548250104

###

GET http://viacep.com.br/ws/53132010/json/

###

GET https://renebizelli-go-weather-799601504925.us-central1.run.app/cep/03132010
