
extensions:
  health_check:
    endpoint: "localhost:13133" 

receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: localhost:4317
    tls:
      insecure: true

processors:
  batch:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
