receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "otel-collector:4317"

exporters:
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans

  debug:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, zipkin]